github.com:
    user: phalanx-hk
    oauth_token: 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
    git_protocol: https
    users:
        phalanx-hk:
            oauth_token: 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
