name: shell lint

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  shell_lint:
    name: shell_lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt install -y shellcheck

      - name: Run ShellCheck
        run: shellcheck ./ubuntu/scripts/* ./mac/setup.sh
