name: macOS

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        run: make mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
