name: macOS

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install just
        env:
          INSTALL_DIR: $HOME/.local/bin
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to $INSTALL_DIR
          export PATH="$INSTALL_DIR:$PATH"

      - name: Setup
        run: just mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
