name: macOS

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  macOS:
    name: macOS
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
              
      - name: Setup
        run: |
          cd mac
          chmod +x setup.sh
          sh setup.sh
