name: macOS

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Configure Homebrew cache
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Caches/Homebrew
            ~/Library/Caches/Homebrew/downloads
          key: ${{ runner.os }}-brew-${{ hashFiles('**/Brewfile.lock.json') }}
      - name: Setup
        run: make mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
