name: macOS

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'

jobs:
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: install just
        uses: extractions/setup-just@v1
        with:
          just-version: 0.8
      - name: Setup
        run: just mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
