name: Ubuntu

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup faketty
        uses: Yuri6037/Action-FakeTTY@v1.1
      
      - name: Install xh
        run: curl -sfL https://raw.githubusercontent.com/ducaale/xh/master/install.sh | faketty sh
      
      - name: Setup
        run: |
          cd ubuntu/scripts/
          chmod +x setup.bash
          /bin/bash setup.bash
