name: Ubuntu

on: 
  push:
    branches: main
    path-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup
        run: |
          cd ubuntu/scripts/
          chmod +x setup.bash
          /bin/bash setup.bash
