name: ubuntu

on: 
  push:
    branches: main
    paths-ignore:
      - 'README.md'
      - 'install/mac/**'
      - '.github/workflows/mac.yml'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: main
    paths-ignore:
      - 'README.md'
      - 'install/mac/**'
      - '.github/workflows/mac.yml'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  ubuntu:
    name: ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["linux/amd64"]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with: 
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup
        run: make ubuntu
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
